### ISSUE TITLE
Example in README is not working in 0.14

### ISSUE THREAD

**Issue by Sergiodiaz53-Dedalus** [kubeflow/katib#2087]
/kind bug

I have installed kubeflow-katib using !pip inside a kubeflow notebook and I have copied the example in the readme. Im looking for a way to run experiments using katib from the sdk.

Im getting a `module 'kubeflow.katib' has no attribute 'search'`
Is the readme out of date or Im using the wrong version?

I have check the documentation but that seems to be outdated. Is there any way to compile it locally? 
Thanks in advance

**Environment:**

- Katib version: 0.14
- Kubernetes version: (`kubectl version`): 1.8.4

---

Impacted by this bug? Give it a 👍 We prioritize the issues with the most 👍

**Comment by tenzen-y** [comment]
@Sergiodiaz53-Dedalus Thanks for creating this.
Does that mean the following `QuickStart` section?

https://github.com/kubeflow/katib#quickstart

If so, you must install the master branch katib to your cluster because we will introduce a new Katib SDK like the `QuickStart` since katib v0.15.0 (not released).

**Comment by Sergiodiaz53-Dedalus** [comment]
Oh! my bad.

Yes, I was talking about that example.
I will install katib 0.15 and will try again then.

Thank you so much for your fast answer!

**Comment by tenzen-y** [comment]
I'm happy I could be of help :)
Since katib v0.15.0 is not released, you can install katib and katib-sdk using the master branch.

install katib : `kubectl apply -k "github.com/kubeflow/katib.git/manifests/v1beta1/installs/katib-standalone?ref=master"`
install katib-sdk: `pip install git+https://github.com/kubeflow/katib.git@master#subdirectory=sdk/python/v1beta1`
